import type { Locale } from "@/lib/i18n";

export const uiCopy = {
  en: {
    official: "Official", youtube: "YouTube", exploreEyebrow: "Explore", grownups: "For grown-ups", parentsPrivacy: "Parents & Privacy", footerTagline: "Vania & Sophia • Family-friendly fun", vaniaDesc: "Adventure • stories • play", sophiaDesc: "Creativity • smiles • imagination", latestCards: ["Stories", "Challenges", "Sisters Together"], latestCardText: "Watch on the official Vaphia channel",
    places: ["Cozy House", "Magic Garden", "Fun Park", "Art Room", "Sweet Kitchen", "Story Corner"],
    placeDescriptions: ["Everyday sister adventures", "Nature, imagination and discovery", "Challenges and playful games", "Drawing and coloring", "Family-friendly kitchen fun", "Stories and quiet-time creativity"],
    watchCards: ["Adventures", "Shorts", "Sisters Together"],
    watchDescriptions: ["Longer family-friendly Vaphia stories and activities.", "Quick, playful moments with Vania and Sophia.", "Favorite moments featuring both sisters."],
    channel: "Official channel: @vaphia",
    aboutVania: "Adventure, stories, play and sister moments.", aboutSophia: "Creativity, imagination, color and joyful activities.", aboutTogether: "Vaphia brings their shared world together through videos, games and creative activities.", together: "Together",
    gameNoLogin: "No child login. No email.", stars: "Vaphia Stars", moves: "Moves", playAgain: "Play again", startGame: "Start game", shuffle: "Shuffle", catchStar: "Catch the star", catchInstruction: "Tap as many stars as you can in 20 seconds.", memoryTitle: "Find the pairs", pictureTitle: "Put Vaphia together", greatJob: "Great job!", solved: "You solved it!", score: "Score",
    doodle: "Doodle Pad", drawAnything: "Draw anything", eraser: "Eraser", clear: "Clear", coloringStudio: "Coloring Studio", colorInstruction: "Tap a color, then a shape", printable: "Printable", coloringPage: "Vaphia coloring page", printableText: "Download a simple black-and-white page to color on paper.", download: "Download SVG",
    grownupCheck: "Grown-up check", unlockParent: "Unlock parent settings", unlockText: "A grown-up can answer:", answerLabel: "Answer", unlock: "Unlock", tryAgain: "Please try again.", externalLink: "External link", gateText: "This link leaves Vaphia. A grown-up can answer:", continue: "Continue", close: "Close",
    deviceControls: "Device controls", parentSettings: "Parent settings", siteSounds: "Site sounds", siteSoundsText: "Keep sounds off by default or allow future game sounds.", animations: "Animations", animationsText: "Turn playful motion on or reduce animation on this device.", externalLinks: "External links", externalLinksText: "Allow direct links to social platforms. When off, the grown-up gate remains active.", resetStars: "Reset Vaphia Stars on this device", savedDevice: "Saved on this device.",
    privacyCards: ["No child account required", "Local progress", "External-link gate", "Private admin", "Privacy-first default", "Adult contact only"],
    privacyDescriptions: ["Games and creative activities work without asking a child for an email address, real name, school, birthday or location.", "Vaphia Stars and parent preferences are stored on the device in local storage. They are not a public child profile.", "Social links use a grown-up check before leaving Vaphia unless a parent enables direct external links on that device.", "Website editing is separated from the child experience and uses authenticated administrator access when Supabase is connected.", "No advertising pixels, behavioral ads, or child analytics are included in this starter build.", "Future contact or partnership forms should be clearly marked for adults and kept out of child game flows."],
    privacyNotice: "Privacy notice", privacyNoticeText: "This site is intentionally designed to minimize collection of children’s personal information. Before public launch, any future analytics, advertising, forms, accounts, purchases or messaging features should be reviewed for the laws that apply to the audiences and countries you target."
  },
  fa: {
    official: "رسمی", youtube: "یوتیوب", exploreEyebrow: "کشف کن", grownups: "برای بزرگ‌ترها", parentsPrivacy: "والدین و حریم خصوصی", footerTagline: "وانیا و سوفیا • سرگرمی خانوادگی", vaniaDesc: "ماجراجویی • داستان • بازی", sophiaDesc: "خلاقیت • لبخند • تخیل", latestCards: ["داستان‌ها", "چالش‌ها", "خواهرها با هم"], latestCardText: "تماشا در کانال رسمی وافیا",
    places: ["خانه دنج", "باغ جادویی", "پارک بازی", "اتاق هنر", "آشپزخانه شیرین", "گوشه داستان"],
    placeDescriptions: ["ماجراجویی‌های روزمره خواهرها", "طبیعت، تخیل و کشف", "چالش‌ها و بازی‌های شاد", "نقاشی و رنگ‌آمیزی", "سرگرمی خانوادگی در آشپزخانه", "داستان و فعالیت‌های آرام"],
    watchCards: ["ماجراجویی‌ها", "ویدیوهای کوتاه", "خواهرها با هم"],
    watchDescriptions: ["داستان‌ها و فعالیت‌های خانوادگی بلندتر وافیا.", "لحظه‌های کوتاه و شاد وانیا و سوفیا.", "لحظه‌های محبوب با حضور هر دو خواهر."],
    channel: "کانال رسمی: @vaphia",
    aboutVania: "ماجراجویی، داستان، بازی و لحظه‌های خواهرانه.", aboutSophia: "خلاقیت، تخیل، رنگ و فعالیت‌های شاد.", aboutTogether: "وافیا دنیای مشترک آن‌ها را با ویدیو، بازی و فعالیت‌های خلاقانه کنار هم می‌آورد.", together: "با هم",
    gameNoLogin: "بدون حساب کودک و بدون ایمیل.", stars: "ستاره‌های وافیا", moves: "حرکت", playAgain: "دوباره بازی کن", startGame: "شروع بازی", shuffle: "دوباره بچین", catchStar: "ستاره را بگیر", catchInstruction: "در ۲۰ ثانیه هرچقدر می‌توانی ستاره بگیر.", memoryTitle: "جفت‌ها را پیدا کن", pictureTitle: "عکس وافیا را کامل کن", greatJob: "آفرین!", solved: "حلش کردی!", score: "امتیاز",
    doodle: "صفحه نقاشی", drawAnything: "هرچی دوست داری بکش", eraser: "پاک‌کن", clear: "پاک کردن", coloringStudio: "استودیوی رنگ‌آمیزی", colorInstruction: "یک رنگ و بعد یک شکل را بزن", printable: "قابل چاپ", coloringPage: "صفحه رنگ‌آمیزی وافیا", printableText: "یک صفحه سیاه‌وسفید ساده برای رنگ‌آمیزی روی کاغذ دانلود کن.", download: "دانلود SVG",
    grownupCheck: "بررسی بزرگ‌تر", unlockParent: "باز کردن تنظیمات والدین", unlockText: "یک بزرگ‌تر پاسخ دهد:", answerLabel: "پاسخ", unlock: "باز کردن", tryAgain: "دوباره تلاش کنید.", externalLink: "لینک خارجی", gateText: "این لینک از وافیا خارج می‌شود. یک بزرگ‌تر پاسخ دهد:", continue: "ادامه", close: "بستن",
    deviceControls: "کنترل‌های دستگاه", parentSettings: "تنظیمات والدین", siteSounds: "صدای سایت", siteSoundsText: "صداها پیش‌فرض خاموش باشند یا صدای بازی‌های آینده فعال شود.", animations: "انیمیشن‌ها", animationsText: "حرکت‌های شاد را روشن نگه دارید یا روی این دستگاه کمتر کنید.", externalLinks: "لینک‌های خارجی", externalLinksText: "لینک مستقیم شبکه‌های اجتماعی را فعال کنید. در حالت خاموش، بررسی بزرگ‌تر فعال می‌ماند.", resetStars: "پاک کردن ستاره‌های وافیا روی این دستگاه", savedDevice: "روی این دستگاه ذخیره شد.",
    privacyCards: ["بدون نیاز به حساب کودک", "پیشرفت محلی", "محافظ لینک خارجی", "پنل ادمین خصوصی", "حریم خصوصی پیش‌فرض", "تماس فقط برای بزرگ‌ترها"],
    privacyDescriptions: ["بازی‌ها و فعالیت‌ها بدون درخواست ایمیل، نام واقعی، مدرسه، تاریخ تولد یا موقعیت کودک کار می‌کنند.", "ستاره‌های وافیا و تنظیمات والدین فقط در حافظه همین دستگاه ذخیره می‌شوند و پروفایل عمومی کودک نیستند.", "لینک‌های اجتماعی قبل از خروج از وافیا بررسی بزرگ‌تر دارند مگر اینکه والد آن را روی دستگاه فعال کند.", "ویرایش سایت از تجربه کودک جداست و پس از اتصال Supabase با دسترسی ادمین احراز هویت‌شده انجام می‌شود.", "در این نسخه پیکسل تبلیغاتی، تبلیغ رفتاری یا آنالیتیکس کودک قرار داده نشده است.", "فرم‌های تماس یا همکاری آینده باید مخصوص بزرگ‌ترها باشند و وارد مسیر بازی کودک نشوند."],
    privacyNotice: "اطلاعیه حریم خصوصی", privacyNoticeText: "این سایت از ابتدا برای حداقل‌کردن جمع‌آوری اطلاعات شخصی کودکان طراحی شده است. پیش از انتشار عمومی، هر قابلیت آینده مثل آنالیتیکس، تبلیغات، فرم، حساب کاربری، خرید یا پیام‌رسانی باید با قوانین کشورهای هدف بررسی شود."
  },
  fr: {
    official: "Officiel", youtube: "YouTube", exploreEyebrow: "Explorer", grownups: "Pour les adultes", parentsPrivacy: "Parents & confidentialité", footerTagline: "Vania & Sophia • Divertissement familial", vaniaDesc: "Aventure • histoires • jeux", sophiaDesc: "Créativité • sourires • imagination", latestCards: ["Histoires", "Défis", "Les sœurs ensemble"], latestCardText: "Voir sur la chaîne officielle Vaphia",
    places: ["Maison douillette", "Jardin magique", "Parc amusant", "Atelier d’art", "Cuisine sucrée", "Coin histoires"], placeDescriptions: ["Aventures quotidiennes", "Nature, imagination et découverte", "Défis et jeux", "Dessin et coloriage", "Cuisine en famille", "Histoires et activités calmes"],
    watchCards: ["Aventures", "Shorts", "Les sœurs ensemble"], watchDescriptions: ["Histoires et activités familiales plus longues.", "Moments courts et amusants avec Vania et Sophia.", "Moments préférés avec les deux sœurs."], channel: "Chaîne officielle : @vaphia",
    aboutVania: "Aventure, histoires, jeux et moments entre sœurs.", aboutSophia: "Créativité, imagination, couleurs et activités joyeuses.", aboutTogether: "Vaphia réunit leur univers à travers des vidéos, jeux et activités créatives.", together: "Ensemble",
    gameNoLogin: "Aucun compte enfant. Aucun e-mail.", stars: "Étoiles Vaphia", moves: "Coups", playAgain: "Rejouer", startGame: "Commencer", shuffle: "Mélanger", catchStar: "Attrape l’étoile", catchInstruction: "Touchez autant d’étoiles que possible en 20 secondes.", memoryTitle: "Trouve les paires", pictureTitle: "Recompose Vaphia", greatJob: "Bravo !", solved: "Puzzle réussi !", score: "Score",
    doodle: "Carnet de dessin", drawAnything: "Dessine ce que tu veux", eraser: "Gomme", clear: "Effacer", coloringStudio: "Atelier coloriage", colorInstruction: "Choisis une couleur puis une forme", printable: "À imprimer", coloringPage: "Coloriage Vaphia", printableText: "Télécharge une page noir et blanc simple à colorier sur papier.", download: "Télécharger SVG",
    grownupCheck: "Vérification adulte", unlockParent: "Déverrouiller les réglages parents", unlockText: "Un adulte peut répondre :", answerLabel: "Réponse", unlock: "Déverrouiller", tryAgain: "Veuillez réessayer.", externalLink: "Lien externe", gateText: "Ce lien quitte Vaphia. Un adulte peut répondre :", continue: "Continuer", close: "Fermer",
    deviceControls: "Réglages appareil", parentSettings: "Réglages parents", siteSounds: "Sons du site", siteSoundsText: "Garder les sons désactivés par défaut ou autoriser les futurs sons de jeu.", animations: "Animations", animationsText: "Activer les mouvements ludiques ou réduire les animations sur cet appareil.", externalLinks: "Liens externes", externalLinksText: "Autoriser les liens directs vers les réseaux sociaux. Sinon, la vérification adulte reste active.", resetStars: "Réinitialiser les étoiles Vaphia", savedDevice: "Enregistré sur cet appareil.",
    privacyCards: ["Aucun compte enfant requis", "Progression locale", "Vérification des liens externes", "Admin privé", "Confidentialité par défaut", "Contact réservé aux adultes"], privacyDescriptions: ["Les jeux fonctionnent sans demander e-mail, vrai nom, école, anniversaire ou localisation à l’enfant.", "Les étoiles Vaphia et réglages parents restent dans le stockage local de l’appareil.", "Les liens sociaux utilisent une vérification adulte avant de quitter Vaphia.", "L’édition du site est séparée de l’expérience enfant et protégée par authentification lorsque Supabase est connecté.", "Aucun pixel publicitaire, publicité comportementale ou analyse enfant n’est inclus par défaut.", "Les futurs formulaires de contact ou partenariat doivent être réservés aux adultes."],
    privacyNotice: "Avis de confidentialité", privacyNoticeText: "Ce site est conçu pour minimiser la collecte de données personnelles des enfants. Avant le lancement public, toute future fonction d’analyse, publicité, formulaire, compte, achat ou messagerie doit être examinée selon les lois applicables."
  },
  es: {
    official: "Oficial", youtube: "YouTube", exploreEyebrow: "Explorar", grownups: "Para adultos", parentsPrivacy: "Padres y privacidad", footerTagline: "Vania & Sophia • Diversión familiar", vaniaDesc: "Aventura • historias • juegos", sophiaDesc: "Creatividad • sonrisas • imaginación", latestCards: ["Historias", "Retos", "Hermanas juntas"], latestCardText: "Ver en el canal oficial de Vaphia",
    places: ["Casa acogedora", "Jardín mágico", "Parque divertido", "Sala de arte", "Cocina dulce", "Rincón de cuentos"], placeDescriptions: ["Aventuras diarias", "Naturaleza, imaginación y descubrimiento", "Retos y juegos", "Dibujo y coloreado", "Diversión familiar en la cocina", "Historias y actividades tranquilas"],
    watchCards: ["Aventuras", "Shorts", "Hermanas juntas"], watchDescriptions: ["Historias y actividades familiares más largas.", "Momentos cortos y divertidos con Vania y Sophia.", "Momentos favoritos con las dos hermanas."], channel: "Canal oficial: @vaphia",
    aboutVania: "Aventura, historias, juegos y momentos entre hermanas.", aboutSophia: "Creatividad, imaginación, color y actividades alegres.", aboutTogether: "Vaphia une su mundo compartido mediante videos, juegos y actividades creativas.", together: "Juntas",
    gameNoLogin: "Sin cuenta infantil. Sin correo electrónico.", stars: "Estrellas Vaphia", moves: "Movimientos", playAgain: "Jugar otra vez", startGame: "Empezar", shuffle: "Mezclar", catchStar: "Atrapa la estrella", catchInstruction: "Toca tantas estrellas como puedas en 20 segundos.", memoryTitle: "Encuentra las parejas", pictureTitle: "Completa Vaphia", greatJob: "¡Muy bien!", solved: "¡Lo resolviste!", score: "Puntuación",
    doodle: "Bloc de dibujo", drawAnything: "Dibuja lo que quieras", eraser: "Borrador", clear: "Borrar", coloringStudio: "Estudio de color", colorInstruction: "Elige un color y luego una forma", printable: "Imprimible", coloringPage: "Página para colorear Vaphia", printableText: "Descarga una página sencilla en blanco y negro para colorear en papel.", download: "Descargar SVG",
    grownupCheck: "Comprobación de adulto", unlockParent: "Desbloquear ajustes para padres", unlockText: "Un adulto puede responder:", answerLabel: "Respuesta", unlock: "Desbloquear", tryAgain: "Inténtalo de nuevo.", externalLink: "Enlace externo", gateText: "Este enlace sale de Vaphia. Un adulto puede responder:", continue: "Continuar", close: "Cerrar",
    deviceControls: "Controles del dispositivo", parentSettings: "Ajustes para padres", siteSounds: "Sonidos del sitio", siteSoundsText: "Mantén los sonidos apagados por defecto o permite futuros sonidos de juegos.", animations: "Animaciones", animationsText: "Activa el movimiento divertido o reduce las animaciones en este dispositivo.", externalLinks: "Enlaces externos", externalLinksText: "Permite enlaces directos a redes sociales. Si está desactivado, la comprobación de adulto sigue activa.", resetStars: "Reiniciar Estrellas Vaphia", savedDevice: "Guardado en este dispositivo.",
    privacyCards: ["Sin cuenta infantil", "Progreso local", "Control de enlaces externos", "Admin privado", "Privacidad por defecto", "Contacto solo para adultos"], privacyDescriptions: ["Los juegos funcionan sin pedir correo, nombre real, escuela, cumpleaños o ubicación del niño.", "Las Estrellas Vaphia y los ajustes parentales se guardan localmente en el dispositivo.", "Los enlaces sociales usan una comprobación de adulto antes de salir de Vaphia.", "La edición del sitio está separada de la experiencia infantil y protegida por autenticación cuando Supabase está conectado.", "No se incluyen píxeles publicitarios, publicidad conductual ni analítica infantil por defecto.", "Los futuros formularios de contacto o colaboración deben estar claramente destinados a adultos."],
    privacyNotice: "Aviso de privacidad", privacyNoticeText: "Este sitio está diseñado para minimizar la recopilación de datos personales de niños. Antes del lanzamiento público, cualquier futura función de analítica, publicidad, formularios, cuentas, compras o mensajería debe revisarse según las leyes aplicables."
  }
} satisfies Record<Locale, Record<string, unknown>>;
